### ISSUE TITLE
chain commands together

### ISSUE THREAD

**Issue by jungle-boogie** [mehrdadrad/mylg#43]
Hi,

Instead of this:
```
local> ns
ns> connect iceland
ns/iceland> node reykjavik
ns/iceland/reykjavik>
```

Could `ns connect iceland reykjavik` be used?

running that command at the shell prompt generates a panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x80e6cea]

goroutine 1 [running]:
panic(0x8524140, 0x39422008)
        /usr/local/go/src/runtime/panic.go:500 +0x334
github.com/mehrdadrad/mylg/cli.(*Readline).UpdateCompleter(0x0, 0x858a8f6, 0x7, 0x0, 0x0, 0x0)
        /home/user/bin/gopath/src/github.com/mehrdadrad/mylg/cli/cli.go:130 +0x8a
main.setNS()
        /home/user/bin/mylg/mylg.go:494 +0x64
main.main()
        /home/user/bin/mylg/mylg.go:129 +0xfd
```

**Comment by mehrdadrad** [comment]
It doesn't support chaining the commands.
