### ISSUE TITLE
Panic Error

### ISSUE THREAD

**Issue by llcamargo** [mehrdadrad/mylg#78]
Hello.

Anyone with this error?
Just logged in and i have error.

=================================================	
                          _    ___ 
                _ __ _  _| |  / __|
               | '  \ || | |_| (_ |
               |_|_|_\_, |____\___|
                      |__/          
	
                 My Looking Glass
           Free Network Diagnostic Tool
                  http://mylg.io
================== myLG v0.2.6 ==================
local> 
local> 
local> panic: runtime error: index out of range

goroutine 7 [running]:
panic(0x905420, 0xc42000c0d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mehrdadrad/mylg/ns.fetchNSHosts(0x0, 0x0, 0x0)
	/home/vagrant/golang/src/github.com/mehrdadrad/mylg/ns/ns.go:357 +0x98d
github.com/mehrdadrad/mylg/ns.(*Request).Init(0xc42004a770)
	/home/vagrant/golang/src/github.com/mehrdadrad/mylg/ns/ns.go:99 +0x7f
created by main.init.1
	/home/vagrant/golang/src/github.com/mehrdadrad/mylg/mylg.go:104 +0x125
axtelecom@laboratorio:~/pacotes$ 

Regards,
Leandro de Lima Camargo

**Comment by mehrdadrad** [comment]
@llcamargo i fixed it today, if you get latest code and compile you shouldn't get this error. please confirm. I'll try to make packages (mac/ubuntu ....)

**Comment by llcamargo** [comment]
I using MAC but i don't know how to compile. I'll search how to.
Thanks.

**Comment by llcamargo** [comment]
@mehrdadrad 
I just run the command: 
`brew install homebrew/dupes/libpcap `
And works again!
Is it right?

Thanks.

**Comment by mehrdadrad** [comment]
@llcamargo that's not related. the root cause of the issue related to a CSV file that it downloads from a 3rd party website and there is a uncompleted line that myLG (not latest code) doesn't validate and causes crash. the latest code fixed also I asked the 3rd party website if they can fix it.

**Comment by mehrdadrad** [comment]
@llcamargo I'm seeing the issue fixed at CSV file (3rd party website). so it should be worked w/ old version as well.

**Comment by FHRNet** [comment]
I'm seeing those exact errors quite frequently. The CSV file can be opened in browser with no problems.

**Comment by mehrdadrad** [comment]
@FHRNet what's the myLG version?

**Comment by FHRNet** [comment]
v0.2.6 on Mac. Happens on Linux too.

It’s currently working. But as I said, sometimes it works, sometimes it throws that error.

**Comment by mehrdadrad** [comment]
I see but no idea why a field that myLG expects to have is not exists for few lines at CSV file, it fixed in v0.2.7 to skip those lines but the Mac package is not available for latest version you have to compile it w/ the latest version code from github.

**Comment by FHRNet** [comment]
Here's the CSV from the time it didn't work, maybe it'll help: https://expirebox.com/download/bf55d5136a1d82a50e6dac8112471f9f.html

**Comment by mehrdadrad** [comment]
@FHRNet thank for ur help but already it fixed in the new version. try to compile from latest code

**Comment by luckman212** [comment]
Any instructions for compiling for macOS? Just use XCode?
